### PR TITLE
Update to 3.1.4 dependencies and style

### PR DESCRIPTION
**Pull request by benmurden**
Tests have been largely rewritten to use new Mocha methods and pass correctly.

### CODE REVIEW

**Review by Robdel12 — APPROVED** [review]
Very nice! Thank you for the PR 😁

**Comment by Robdel12** [comment]
I'll get around to releasing this before lunch today (Central Time)

**Comment by benmurden** [comment]
Thanks for the quick turnaround!

**Comment by Robdel12** [comment]
Should be good to go here! :D

**Pull request merged**
